codecov:
  # Avoid "Missing base report" issues
  allow_coverage_offsets: true
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2         # decimal places to display: 0 <= value <= 4
  round: nearest
  range: 50...90      # custom range of coverage colors from red -> yellow -> green

  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
    patch:
      default:
        target: auto
        threshold: 5%
        base: auto

github_checks:
    annotations: false

# Code coverage data needs to be relative to the repo root, but in out reports it's
# relative to /home/circleci/scalyr-agent-2/ so we need to fix the paths so it works
# correctly on codecov.io
fixes:
  - "/home/circleci/scalyr-agent-2/::"
  - "/home/runner/work/scalyr-agent-2/scalyr-agent-2/::"
  - "/Users/runner/work/scalyr-agent-2/scalyr-agent-2/::"
  - "/usr/share/scalyr-agent-2/py/::"

ignore:
  # Ignore tests directories for which we currently don't generate coverage
  # currently don't generate coverage
  - "/home/circleci/scalyr-agent-2/tests/ami"
  - "/home/circleci/scalyr-agent-2/tests/distribution"
  - "/home/circleci/scalyr-agent-2/tests/distribution_builders"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
