codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2         # decimal places to display: 0 <= value <= 4
  round: nearest
  range: 50...90      # custom range of coverage colors from red -> yellow -> green

  status:
    project:
      default:
        default: false
        # TODO: Define threshold once we agree on them
        #target: auto
        #threshold: 2%
        #patch: yes

# Code coverage data is relative to scalyr_agent/ directory so we need to
# prepend it for codecov.io web reports to work correctly since those rely
# on paths relative to the repo root
fixes:
    - "::scalyr_agent/"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
