FROM ubuntu
MAINTAINER Scalyr Inc <support@scalyr.com>
RUN apt-get update && \
    apt-get install -y \
        apt-transport-https \
        python \
        wget \
        && \
    apt-get clean && \
    cd /usr/bin && \
    mkdir -p /tmp/scalyr
#END RUN
COPY {SCALYR_PKG} /tmp/scalyr/
RUN cd /tmp/scalyr && \
    dpkg -i {SCALYR_PKG} && \
    cd / && \
    rm -rf /tmp/scalyr
#END RUN
CMD ["/usr/sbin/scalyr-agent-2", "--no-fork", "start" ]
