FROM ubuntu:16.04
ENV DEBIAN_FRONTEND noninteractive
MAINTAINER Scalyr Inc <support@scalyr.com>
RUN apt-get update && apt-get install -y \
  apt-transport-https \ 
  build-essential \
  gcc \
  git \  
  python \
  ruby-dev \
  wget && \
  apt-get clean
RUN gem install fpm
RUN cd /usr/bin && mkdir -p /tmp/scalyr && \
  git config --global user.name "Scalyr" && git config --global user.email support@scalyr.com && \
  git clone git://github.com/scalyr/scalyr-agent-2.git /tmp/scalyr && \
  cd /tmp/scalyr && \ 
  python build_package.py deb && \
  dpkg -i scalyr-agent-2_2.0.14_all.deb && \
  cd / && \
  rm -rf /tmp/scalyr
CMD ["/usr/sbin/scalyr-agent-2", "--no-fork", "--no-change-user", "start"]