{fpm_package_builder_dockerfile}
ADD ./agent_source /agent_source
WORKDIR /package
RUN python /agent_source/build_package.py rpm
FROM amazonlinux
RUN yum install -y initscripts {python_version}
RUN yum groupinstall -y 'Development Tools'
RUN yum install -y {python_version}-pip {python_version}-devel

COPY agent_source/dev-requirements.txt dev-requirements.txt
COPY agent_source/extra-requirements.txt extra-requirements.txt

RUN {python_version} -m pip install -r dev-requirements.txt
RUN {python_version} -m pip install -r extra-requirements.txt

COPY --from=fpm_package_builder /package/scalyr-agent*.rpm /scalyr-agent.rpm
COPY --from=fpm_package_builder /agent_source /agent_source

RUN rpm -i scalyr-agent.rpm
RUN ln -s -f /usr/bin/{python_version} /usr/bin/python
WORKDIR /agent_source
ENV PYTHONPATH=.:${{PYTHONPATH}}