apiVersion: v1
kind: ConfigMap
data:
  SCALYR_K8S_CLUSTER_NAME: <your_cluster_name>
  #
  # EU customers must uncomment this next line:
  # SCALYR_SERVER: "https://upload.eu.scalyr.com"
  #
  # Define any other environment variables for config variables that are "environment aware".
  # Most environment variables start with "SCALYR_"
  # See https://www.scalyr.com/help/scalyr-agent#environmentAware for more details.
  #
  # Example:
  # SCALYR_K8S_EVENTS_DISABLE: "true"
  #
metadata:
  name: scalyr-config
  namespace: default
