#!/opt/scalyr-agent-2-dependencies/bin/python3
# Copyright 2014-2023 Scalyr Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import subprocess
import sys
import os
import pathlib as pl

PYTHON_EXECUTABLE_PATH = pl.Path("/opt/scalyr-agent-2-dependencies/bin/python3")


def _set_openssl():
    verify_sll_script = pl.Path(__file__) / "verify_openssl.py"
    subprocess.check_call(
        [
            str(PYTHON_EXECUTABLE_PATH),
            str(verify_sll_script)
        ]
    )


def handle_dependencies_config_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "dependencies-config",
    )
    parser.add_argument(
        "command",
        choices=["recreate-venv"]
    )
    args = parser.parse_args()

    if args.command == "recreate-venv":
        recreate_venv_executable = pl.Path("/opt/scalyr-agent-2-dependencies/bin/recreate-venv")
        os.execv(str(recreate_venv_executable), [])


if __name__ == '__main__':
    command = None

    argv = sys.argv[:]

    if argv:
        if argv[0] == __file__:
            argv.pop(0)

    if argv:
        command = argv[0]

    if command == "dependencies-config":
        handle_dependencies_config_args()
    else:
        venv_python_executable = "/var/opt/scalyr-agent-2-dependencies/venv/bin/python3"
        argv = [venv_python_executable, "/usr/share/scalyr-agent-2/py/scalyr_agent/agent_main.py", *argv]
        os.execv(venv_python_executable, argv)





