#!/usr/bin/env bash
# Copyright 2014-2022 Scalyr Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PYTHON_SUBDIR_NAME="scalyr-agent-2-dependencies"

export LD_LIBRARY_PATH="/usr/lib/${PYTHON_SUBDIR_NAME}"
export PYTHONPATH="/usr/lib/${PYTHON_SUBDIR_NAME}/python3.10:/usr/lib/${PYTHON_SUBDIR_NAME}/python3.10/lib-dynload:/usr/lib/${PYTHON_SUBDIR_NAME}/python3.10/site-packages"
exec /usr/libexec/scalyr-agent-2-dependencies/python3 "$@"