# Copyright 2014-2020 Scalyr Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Module responsible for parsing data from build_info file which is available with each agent package.

Keep in mind that that file is only available for package and not for dev installs.
"""

from __future__ import unicode_literals
from __future__ import absolute_import

if False:
    from typing import Dict

import os
import subprocess
from io import open

import six

try:
    from __scalyr__ import DEV_INSTALL
except ImportError:
    from scalyr_agent.__scalyr__ import DEV_INSTALL

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
BUILD_INFO_PATH = os.path.abspath(os.path.join(BASE_DIR, "../build_info"))

GIT_GET_HEAD_REVISION_CMD = "git rev-parse HEAD"


def get_build_info():
    # type: () -> Dict[str, str]
    """
    Return sanitized dictionary populated with data from build_info file.
    """
    if not os.path.isfile(BUILD_INFO_PATH):
        return {}

    with open(BUILD_INFO_PATH, "r") as fp:
        content = fp.read()

    result = {}

    for line in content.strip().split("\n"):
        line = line.strip()
        key, value = line.split(":", 1)
        key = key.strip().lower().replace(" ", "_")
        value = value.strip()
        result[key] = value

    return result


def get_build_revision_from_git():
    # type: () -> str
    """
    Return build revision from git ref log (if available).

    NOTE: This function is only used on dev (non-package) installs.
    """
    cmd = GIT_GET_HEAD_REVISION_CMD

    try:
        output = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)
    except Exception:
        return "unknown"

    return six.ensure_text(output).strip()


def get_build_revision():
    # type: () -> str
    """
    This function retrieves git commit which was used to build the agent package from the
    build_info file which is generated by build_package.py script.

    If we are running on a dev install, it retrieves the commit revision by querying git reflog
    instead.
    """
    if not os.path.isfile(BUILD_INFO_PATH) and DEV_INSTALL:
        return get_build_revision_from_git()

    build_info = get_build_info()
    return build_info.get("latest_commit", "unknown")
