# Copyright 2014-2020 Scalyr Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Module responsible for parsing data from build_info file which is available with each agent package.

Keep in mind that that file is only available for package and not for dev installs.
"""

from __future__ import unicode_literals
from __future__ import absolute_import

if False:  # NOSONAR
    from typing import Dict

import os
import pathlib as pl
from io import open

import six

from scalyr_agent import __scalyr__
from scalyr_agent.compat import subprocess_check_output

GIT_GET_HEAD_REVISION_CMD = "git rev-parse HEAD"

# The build_info file should be located in the install root directory.
BUILD_INFO_FILE_PATH = str(pl.Path(__scalyr__.get_install_root(), "build_info"))


def get_build_info():
    # type: () -> Dict[str, str]
    """
    Return sanitized dictionary populated with data from build_info file.
    """
    if not os.path.isfile(BUILD_INFO_FILE_PATH):
        return {}

    build_info_file_content = pl.Path(BUILD_INFO_FILE_PATH).read_text()

    return _parse_build_info_content(build_info_file_content)


def _parse_build_info_content(content):
    # type: (str) -> Dict[str, str]
    result = {}
    for line in content.strip().split("\n"):
        line = line.strip()

        split = line.split(":", 1)

        if len(split) != 2:
            continue

        key, value = split
        key = key.strip().lower().replace(" ", "_")
        value = value.strip()

        result[key] = value

    return result


def get_build_revision_from_git():
    # type: () -> str
    """
    Return build revision from git ref log (if available).

    NOTE: This function is only used on dev (non-package) installs.
    """
    cmd = GIT_GET_HEAD_REVISION_CMD

    try:
        output = subprocess_check_output(cmd, shell=True)
    except Exception:
        return "unknown"

    return six.ensure_text(output).strip()


def get_build_revision():
    # type: () -> str
    """
    This function retrieves git commit which was used to build the agent package from the
    build_info file which is generated by build_package.py script.

    If we are running on a dev install, it retrieves the commit revision by querying git reflog
    instead.
    """
    # NOTE: We use lazy import to avoid import time side affects
    from scalyr_agent.__scalyr__ import INSTALL_TYPE

    if INSTALL_TYPE == __scalyr__.InstallType.DEV_INSTALL:
        if not pl.Path(BUILD_INFO_FILE_PATH).is_file():
            return get_build_revision_from_git()

    build_info = get_build_info()
    return build_info.get("latest_commit", "unknown")
