# Final Scalyr Agent docker image that uses the previously built base image.
# NOTE: multi-stage builds require Docker 17.05 or greater

## Type of the image build, e.g: docker-json, docker-syslog, k8s
#ARG BUILD_TYPE

# Name of the base image to use.
ARG BASE_IMAGE

# Suffix for the python dockerhub image. For now can be:
#   - 'python:slim' for debian based image
#   - 'python:alpine' for alpine based image.
ARG PYTHON_BASE_IMAGE
ARG DOCKER_IMAGE_TYPE


FROM $BASE_IMAGE as scalyr-build
MAINTAINER Scalyr Inc <support@scalyr.com>

# e.g. k8s, docker-json
ARG DOCKER_IMAGE_TYPE
# e.g. k8s-debian, docker-json-debian, k8s-alpine
ARG BUILDER_NAME
ADD . /scalyr-agent-2

# Build the tarball with Agent's files.
RUN python3 /scalyr-agent-2/agent_build/docker/create_container_tarball.py --config "${DOCKER_IMAGE_TYPE}-config" --output-path /tmp/build

# Extract tarball to the special place that can be reused by next stages.
WORKDIR /tmp/container-fs
RUN tar -xf /tmp/build/scalyr-agent.tar.gz

WORKDIR /

# Copy result files to a new base stage.
FROM $PYTHON_BASE_IMAGE as scalyr-base
MAINTAINER Scalyr Inc <support@scalyr.com>
# Copy Agent's Python dependencies. Those dependencies were built in the base image,
# which is given by 'BASE_IMAGE' arg.
COPY --from=scalyr-build  /tmp/dependencies/ /
# Copy Agent files.
COPY --from=scalyr-build /tmp/container-fs /


# Optional stage for docker-json.
FROM scalyr-base as build-docker-json
MAINTAINER Scalyr Inc <support@scalyr.com>
# Nothing to add

# Optional stage for docker-api.
FROM scalyr-base as build-docker-api
MAINTAINER Scalyr Inc <support@scalyr.com>
# Nothing to add


# Optional stage for docker-syslog.
FROM scalyr-base as build-docker-syslog
MAINTAINER Scalyr Inc <support@scalyr.com>
# expose syslog ports
EXPOSE 601/tcp
# Please note Syslog UDP 1024 max packet length (rfc3164)
EXPOSE 514/udp


# Optional stage for k8s.
FROM scalyr-base as build-k8s
MAINTAINER Scalyr Inc <support@scalyr.com>
ENV SCALYR_STDOUT_SEVERITY ERROR


# Noraml result image.
FROM build-$DOCKER_IMAGE_TYPE as scalyr
MAINTAINER Scalyr Inc <support@scalyr.com>

CMD ["/usr/sbin/scalyr-agent-2", "--no-fork", "--no-change-user", "start"]
