# Base image that creates all necessary dependencies for the scalyr-agent docker image.
# NOTE: multi-stage builds require Docker 17.05 or greater

# Suffix for the python dockerhub image. For now can be:
#   - 'slim' for debian based image
#   - 'alpine' for alpine based image.
ARG PYTHON_BASE_IMAGE_NAME

# Install dependency packages for debian.
FROM $PYTHON_BASE_IMAGE_NAME as base
MAINTAINER Scalyr Inc <support@scalyr.com>

ARG PYTHON_BASE_IMAGE_TYPE


ADD agent_build/docker/install-base-image-common-dependencies.sh agent_build/docker/install-base-image-common-dependencies.sh
RUN PYTHON_BASE_IMAGE_TYPE=$PYTHON_BASE_IMAGE_TYPE sh agent_build/docker/install-base-image-common-dependencies.sh

FROM base as scalyr-dependencies
MAINTAINER Scalyr Inc <support@scalyr.com>

ARG PYTHON_BASE_IMAGE
ARG TARGETVARIANT
ARG COVERAGE_VERSION

ADD agent_build/requirement-files/docker-image-requirements.txt agent_build/requirement-files/docker-image-requirements.txt
ADD agent_build/requirement-files/compression-requirements.txt agent_build/requirement-files/compression-requirements.txt
ADD agent_build/requirement-files/main-requirements.txt agent_build/requirement-files/main-requirements.txt

ADD agent_build/docker/install-base-image-dependencies.sh agent_build/docker/install-base-image-dependencies.sh
ADD agent_build/docker/install-base-image-build-dependencies.sh agent_build/docker/install-base-image-build-dependencies.sh
ADD agent_build/docker/install-base-image-rust.sh agent_build/docker/install-base-image-rust.sh

RUN PYTHON_BASE_IMAGE_TYPE=$PYTHON_BASE_IMAGE_TYPE sh agent_build/docker/install-base-image-build-dependencies.sh
RUN TARGETVARIANT=$TARGETVARIANT PYTHON_BASE_IMAGE_TYPE=$PYTHON_BASE_IMAGE_TYPE sh agent_build/docker/install-base-image-rust.sh
RUN TARGETVARIANT=$TARGETVARIANT PYTHON_BASE_IMAGE_TYPE=$PYTHON_BASE_IMAGE_TYPE sh agent_build/docker/install-base-image-dependencies.sh

# Install packages and tools that will be required during the final image build.
FROM base as ready-base
MAINTAINER Scalyr Inc <support@scalyr.com>

# Copy Agent's Python dependencies, so they also can be used in the final image build.
COPY --from=scalyr-dependencies  /tmp/dependencies/ /tmp/dependencies/
WORKDIR /
