apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: ci-server-k8s
  name: ci-server-k8s
  selfLink: /apis/apps/v1/namespaces/default/deployments/ci-server-k8s
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: ci-server-k8s
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ci-server-k8s
    spec:
      containers:
      - image: 137797084791.dkr.ecr.us-east-2.amazonaws.com/scalyr-dev:latest
        imagePullPolicy: IfNotPresent
        name: ci-server-k8s
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: 
          requests:
            memory: "1.5G"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
