FROM python:2.7-alpine3.9 as scalyr
MAINTAINER Scalyr Inc <support@scalyr.com>
RUN cd /usr/bin && mkdir -p /tmp/scalyr/src && cd /tmp/scalyr && \
  git init && \
  git config --local user.name "Scalyr" && git config --local user.email support@scalyr.com && \
  git clone -b k8s_preview git://github.com/scalyr/scalyr-agent-2.git ./src && \
  cd ./src && \
  python build_package.py --no-versioned-file-name docker_tarball && \
  tar --no-same-owner -C / -zxf /tmp/scalyr/src/scalyr-docker-agent.tar.gz && \
  cd / && \
  rm -rf /tmp/scalyr

EXPOSE 601/tcp
EXPOSE 514/udp

CMD ["/usr/sbin/scalyr-agent-2", "--no-fork", "--no-change-user", "start"]
