# Copyright 2020 Scalyr Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This Dockerfile is primarily meant to be used for testing the Docker monitor functionality in
# various (scenarios - ingesting via json-log file log file on disk, ingesting via API, etc.)
#
# To build the image:
#
# docker build -f docker/Dockerfile.docker_monitor_testing_config -t std-printer scripts/
#
# To run in:
#
# docker run -it --rm -d --name std-printer std-printer -l my-label-1 -l my-label-2 --env SLEEP_DELAY=5
#
# To kill / restart it to test various scenarios:
#
# docker kill "$(docker ps -aqf "name=std-printer")"
#
# docker restart "$(docker ps -aqf "name=std-printer")"
#
# Log files should then be available at ~/scalyr-agent-dev/log/docker-std-printer-stdout.log.

FROM python:3.8-slim as build-image
MAINTAINER Scalyr Inc <support@scalyr.com>

ADD print-to-stdout-stderr.sh /app/print-to-stdout-stderr.sh

ENTRYPOINT ["bash", "/app/print-to-stdout-stderr.sh"]
