FROM ubuntu:16.04
ENV DEBIAN_FRONTEND noninteractive
MAINTAINER Scalyr Inc <support@scalyr.com>
RUN apt-get update && \
    apt-get install -y python-pip && \
    apt-get clean && \
    pip --no-cache-dir install ujson
COPY scalyr-k8s-agent.tar.gz /tmp/
RUN tar --no-same-owner -C / -zxf /tmp/scalyr-k8s-agent.tar.gz && \
  rm /tmp/scalyr-k8s-agent.tar.gz

EXPOSE 601/tcp
EXPOSE 514/udp

CMD ["/usr/sbin/scalyr-agent-2", "--no-fork", "--no-change-user", "start"]
