FROM python:2.7-alpine3.9 as scalyr
MAINTAINER Scalyr Inc <support@scalyr.com>
RUN pip --no-cache-dir install ujson
COPY scalyr-k8s-agent.tar.gz /tmp/
RUN tar --no-same-owner -C / -zxf /tmp/scalyr-k8s-agent.tar.gz && \
  rm /tmp/scalyr-k8s-agent.tar.gz

EXPOSE 601/tcp
EXPOSE 514/udp

CMD ["/usr/sbin/scalyr-agent-2", "--no-fork", "--no-change-user", "start"]
