name: "Init job matrices"
description: "This action accepts matrices for the jobs that are used in the agent-build workflow and excludes job that are must not be executed in mon-master runs."

inputs:
  images-to-build:
    description: "JSON-formatted matrix for images to build."
    required: true

  managed-packages-to-build:
    description: "JSON-formatted matrix for managed packages to build."
    required: true

  managed-packages-to-test:
    description: "JSON-formatted matrix for managed packages to test."
    required: true

  github_token:
    description: 'A Github token'
    required: true

outputs:
  pre_build_steps_matrix_json:
    description: "JSON-formatted job matrix for steps that has to be built in separate jobs."
    value: ${{ steps.get-job-matrices.outputs.pre_build_steps_matrix_json }}
  agent_image_build_matrix_json:
    description: "JSON-formatted job matrix to build images."
    value: ${{ steps.get-job-matrices.outputs.agent_image_build_matrix_json }}
  managed_packages_build_matrix_json:
    description: "JSON-formatted job matrix to build managed packages."
    value: ${{ steps.get-job-matrices.outputs.agent_managed_packages_build_matrix_json }}
  managed_packages_test_matrix_json:
    description: "JSON-formatted job matrix to build managed packages."
    value: ${{ steps.get-job-matrices.outputs.agent_managed_packages_test_matrix_json }}
  is_master_run:
    description: "Boolean flag that indicates (if true) that the workflow runs in master branch or in a pull request against it."
    value: ${{ steps.get-job-matrices.outputs.is_master_run }}
  to_publish:
    description: "Boolean flag that indicates (if true) that the build artifacts have to be published because the workflow runs in master branch or a 'production' tag."
    value: ${{ steps.get-job-matrices.outputs.to_publish }}
  is_production:
    description: "Boolean flag that indicates (if true) that the build artifacts have to be also published as a production artifacts."
    value: ${{ steps.get-job-matrices.outputs.is_production }}
  version:
    description: "Version that has to be assigned for build artifacts."
    value: ${{ steps.get-job-matrices.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get job matrices.
      id: get-job-matrices
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}"
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        DEFAULT_OS: ubuntu-20.04
        DEFAULT_PYTHON_VERSION: 3.8.13
      run: |
        set -e
        
        python3 agent_build_refactored/scripts/get_workflow_info.py > /tmp/workflow_info.json
        IS_MASTER_RUN="$(cat /tmp/workflow_info.json | jq -c '.is_master_run')"
        echo "is_master_run=${IS_MASTER_RUN}" >> $GITHUB_OUTPUT
        echo "to_publish=$(cat /tmp/workflow_info.json | jq -c '.to_publish')" >> $GITHUB_OUTPUT
        echo "is_production=$(cat /tmp/workflow_info.json | jq -c '.is_production')" >> $GITHUB_OUTPUT
        echo "version=$(cat /tmp/workflow_info.json | jq -c '.version')" >> $GITHUB_OUTPUT
        
        mkdir -p /tmp/matrices
        
        cat <<EOT | python3 agent_build_refactored/scripts/filter_matrix_jobs.py --is-master-run "${IS_MASTER_RUN}" > /tmp/matrices/agent_image_build_matrix.json
        ${{ inputs.images-to-build }}
        EOT
        echo "agent_image_build_matrix_json=$(cat /tmp/matrices/agent_image_build_matrix.json)" >> $GITHUB_OUTPUT
        
        cat <<EOT | python3 agent_build_refactored/scripts/filter_matrix_jobs.py --is-master-run "${IS_MASTER_RUN}" > /tmp/matrices/agent_managed_packages_build_matrix.json
        ${{ inputs.managed-packages-to-build }}
        EOT
        echo "agent_managed_packages_build_matrix_json=$(cat /tmp/matrices/agent_managed_packages_build_matrix.json)" >> $GITHUB_OUTPUT
        
        cat <<EOT | python3 agent_build_refactored/scripts/filter_matrix_jobs.py --is-master-run "${IS_MASTER_RUN}" > /tmp/matrices/agent_managed_packages_test_matrix.json
        ${{ inputs.managed-packages-to-test }}
        EOT
        echo "agent_managed_packages_test_matrix_json=$(cat /tmp/matrices/agent_managed_packages_test_matrix.json)" >> $GITHUB_OUTPUT
        
        echo "pre_build_steps_matrix_json=$(python3 agent_build_refactored/scripts/get_steps_to_prebuilt_matrix.py --matrices_path /tmp/matrices)" >> $GITHUB_OUTPUT
        

    - name: Print job matrices
      shell: bash
      run: |
        
        echo -n "Is master run: "
        echo '${{ steps.get-job-matrices.outputs.is_master_run }}' | jq --color-output
        
        echo -n "Is to publish: "
        echo '${{ steps.get-job-matrices.outputs.to_publish }}' | jq --color-output
        
        echo -n "Is production: "
        echo '${{ steps.get-job-matrices.outputs.is_production }}' | jq --color-output
        
        echo -n "Version: "
        echo '${{ steps.get-job-matrices.outputs.version }}' | jq --color-output

        echo "Image pre-build steps job matrix: "
        echo '${{ steps.get-job-matrices.outputs.pre_build_steps_matrix_json }}' | jq --color-output
        
        echo "Image build job matrix: "
        echo '${{ steps.get-job-matrices.outputs.agent_image_build_matrix_json }}' | jq --color-output
        
        echo "Managed packages build job matrix: "
        echo '${{ steps.get-job-matrices.outputs.agent_managed_packages_build_matrix_json }}' | jq --color-output
        
        echo "Managed packages test job matrix: "
        echo '${{ steps.get-job-matrices.outputs.agent_managed_packages_test_matrix_json }}' | jq --color-output
