#!/usr/bin/env bash
# Copyright 2014-2023 Scalyr Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# This script is a wrapper for the virtualenv's Python executable in the package. We need to wrap it in order
# to run it with additional path in 'LD_LIBRARY_PATH' variable.
#
set -e

DEPENDENCIES_ROOT="/opt/scalyr-agent-2-dependencies"
DEPENDENCIES_LIBS="${DEPENDENCIES_ROOT}/lib"

export LD_LIBRARY_PATH="${DEPENDENCIES_LIBS}:${DEPENDENCIES_LIBS}/openssl/current:${LD_LIBRARY_PATH}"
exec "/var/opt/scalyr-agent-2-dependencies/venv/bin/python3" "$@"

