FROM centos:7

# Needed for python-pip package
RUN yum update -y
RUN yum install -y epel-release

RUN yum update -y
RUN yum install -y initscripts gcc
RUN yum install -y python2 python2-devel python2-pip
RUN yum install -y python3 python3-devel python3-pip

COPY dev-requirements.txt dev-requirements.txt

RUN python2 -m pip install -r dev-requirements.txt
RUN python3 -m pip install -r dev-requirements.txt
