
import os
import shutil
import pathlib as pl
import subprocess
import sys

from package_builders.utils.old_build_util import (
    make_path,
    make_directory,
    run_command,
    convert_path,
    recursively_delete_files_by_name,
    recursively_delete_dirs_by_name,
    write_to_file,
    get_install_info,
    cat_files,
    glob_files,
    create_scalyr_uuid3, get_source_root, get_agent_version,
)


from package_builders.utils.builder import Builder

class WindowsBinaryBuilder(Builder):
    NAME = "win32"

    def __init__(self):
        super().__init__()

    def build(self, output_dir: pl.Path):
        output_dir = output_dir.absolute()
        os.chdir(self.work_dir)
        self._build_win32_installer_package(get_agent_version(), "main", output_dir)

    def _build_win32_installer_package(self, version: str, variant: str, output_dir: pl.Path):
        """Builds an MSI that will install the agent on a win32 machine in the current working directory.

        Note, this can only be run on a Windows machine with the proper binaries and packages installed.

        @param version: The agent version.

        @return: The file name of the built package.
        """
        # Ensure that WIX is installed (toolkit to build Windows installers) by verifying its two main binaries are present.
        if not shutil.which('candle') or not shutil.which('light') or not shutil.which('heat'):
            print(
                "Error, the WIX toolset does not appear to be installed.", file=sys.stderr
            )
            print(
                "Please install it to build the Windows Scalyr Agent installer.",
                file=sys.stderr,
            )
            print("See http://wixtoolset.org.", file=sys.stderr)
            sys.exit(1)

        try:
            import psutil  # NOQA
        except ImportError:
            # noinspection PyUnusedLocal
            print(
                "Error, the psutil Python module is not installed.  This is required to build the",
                file=sys.stderr,
            )
            print(
                "Windows version of the Scalyr Agent.  Please download and install it.",
                file=sys.stderr,
            )
            print("See http://pythonhosted.org/psutil/", file=sys.stderr)
            print(
                'On many systems, executing "pip install psutil" will install the package.',
                file=sys.stderr,
            )
            sys.exit(1)

        make_directory("source_root")
        make_directory("data_files")

        agent_source_root = get_source_root()

        # Populate source_root
        os.chdir("source_root")

        shutil.copytree(make_path(agent_source_root, "scalyr_agent"), "scalyr_agent")
        # We have to move __scalyr__.py up to the top of the source_root since, when running in the environment
        # generated by PyInstaller, an 'import __scalyr__.py' will not look in the current directory.. it will only look
        # for that module at the top of the sources_root.  Essentially, the PYTHONPATH variable only has a single
        # entry in it, and it does not have '.' in it.  We leave a copy of __scalyr__.py in the original scalyr_agent
        # directory because we need it there when we execute setup.py.  For the same reason, we put a copy of VERSION.
        shutil.copy(convert_path("scalyr_agent/__scalyr__.py"), "__scalyr__.py")
        shutil.copy(make_path(agent_source_root, "VERSION"), "VERSION")
        shutil.copy(
            make_path(agent_source_root, "VERSION"),
            convert_path("scalyr_agent/VERSION"),
        )

        shutil.copytree(make_path(agent_source_root, "monitors"), "monitors")

        os.chdir("monitors")
        recursively_delete_files_by_name("README.md")
        os.chdir("..")

        # Exclude certain files.
        # TODO:  Should probably use MANIFEST.in to do this, but don't know the Python-fu to do this yet.
        #
        # Don't include the tests directories.  Also, don't include the .idea directory created by IDE.
        recursively_delete_dirs_by_name(r"\.idea", "tests")
        recursively_delete_files_by_name(
            r".*\.pyc", r".*\.pyo", r".*\.pyd", r"all_tests\.py", r".*~"
        )

        # Move back up to the root directory and populate the data_files.
        os.chdir("..")
        os.chdir("data_files")

        # Copy the version file.  We copy it both to the root and the package root.  The package copy is done down below.

        # make it VERSION.txt because PyInstaller on python 2 expects dll file named VERSION,
        # and then fails with an error because of the invalid DLL loading.
        shutil.copy(make_path(agent_source_root, "VERSION"), "VERSION.txt")
        shutil.copy(make_path(agent_source_root, "LICENSE.txt"), "LICENSE.txt")

        # Also add in install_info file
        write_to_file(get_install_info("package"), "install_info.json")

        # Copy the third party licenses
        shutil.copytree(
            make_path(agent_source_root, "scalyr_agent/third_party/licenses"), "licenses"
        )

        os.chdir("..")
        # We need to place a 'setup.py' here so that when we executed py2exe it finds it.
        shutil.copy(make_path(agent_source_root, "setup.py"), "setup.py")

        shutil.copy(
            make_path(agent_source_root, "DESCRIPTION.rst"),
            convert_path("source_root/DESCRIPTION.rst"),
        )

        shutil.copy(
            os.path.join(agent_source_root, "win32", "scalyr_agent.wxs"), "scalyr_agent.wxs"
        )
        shutil.copy(
            os.path.join(agent_source_root, "win32", "wix-heat-bin-transform.xsl"),
            "wix-heat-bin-transform.xsl",
        )

        agent_package_path = os.path.join(agent_source_root, "scalyr_agent")

        add_data = {os.path.join("data_files", "install_info.json"): "scalyr_agent"}

        # Add monitor modules as hidden imports, since they are not directly imported in the agent's code.
        hidden_imports = [
            "scalyr_agent.builtin_monitors.apache_monitor",
            "scalyr_agent.builtin_monitors.graphite_monitor",
            "scalyr_agent.builtin_monitors.mysql_monitor",
            "scalyr_agent.builtin_monitors.nginx_monitor",
            "scalyr_agent.builtin_monitors.shell_monitor",
            "scalyr_agent.builtin_monitors.syslog_monitor",
            "scalyr_agent.builtin_monitors.test_monitor",
            "scalyr_agent.builtin_monitors.url_monitor",
            "scalyr_agent.builtin_monitors.windows_event_log_monitor",
            "scalyr_agent.builtin_monitors.windows_system_metrics",
            "scalyr_agent.builtin_monitors.windows_process_metrics",
            "scalyr_agent.builtin_monitors.openmetrics_monitor",
        ]

        hidden_imports.extend(["win32timezone"])

        # Add packages to frozen binary paths.
        paths_to_include = [
            os.path.join(agent_source_root, "scalyr_agent", "third_party"),
            os.path.join(agent_source_root, "scalyr_agent", "third_party_python2"),
        ]

        # Create --add-data options from previously added files.
        add_data_options = []
        for src, dest in add_data.items():
            add_data_options.append("--add-data")
            add_data_options.append("{}{}{}".format(src, os.path.pathsep, dest))

        # Create --hidden-import options from previously created hidden imports list.
        hidden_import_options = []
        for h in hidden_imports:
            hidden_import_options.append("--hidden-import")
            hidden_import_options.append(str(h))

        paths_options = []
        for p in paths_to_include:
            paths_options.extend(["--paths", p])

        command = [
            sys.executable,
            "-m",
            "PyInstaller",
            os.path.join(agent_package_path, "agent_main.py"),
            "--onedir",
            "-n",
            "scalyr-agent-2",
        ]
        command.extend(add_data_options)
        command.extend(hidden_import_options)
        command.extend(paths_options)
        command.extend(
            [
                "--exclude-module",
                "asyncio",
                "--exclude-module",
                "FixTk",
                "--exclude-module",
                "tcl",
                "--exclude-module",
                "tk",
                "--exclude-module",
                "_tkinter",
                "--exclude-module",
                "tkinter",
                "--exclude-module",
                "Tkinter",
                "--exclude-module",
                "sqlite",
            ]
        )

        try:
            subprocess.run(command, check=True, capture_output=True)
        except subprocess.CalledProcessError as e:
            print("Error building frozen binary: {}".format(e))
            print("stdout: {}".format(e.output.decode("utf-8")))
            print("stderr:")
            for line in e.stderr.decode("utf-8").split("\n"):
                print(line)
            raise

        make_directory("Scalyr/certs")
        make_directory("Scalyr/logs")
        make_directory("Scalyr/data")
        make_directory("Scalyr/config/agent.d")
        make_directory("Scalyr/config/templates")
        make_directory("Scalyr/bin")
        # NOTE: We in intentionally set this permission bit for agent.d directory to make sure it's not
        # readable by others.
        os.chmod("Scalyr/config/agent.d", int("741", 8))

        # Copy the config file.
        agent_json_path = make_path(agent_source_root, "config/agent.json")
        cat_files(
            [agent_json_path],
            "Scalyr/config/templates/agent_config.tmpl",
            convert_newlines=True,
        )
        # NOTE: We in intentionally set this permission bit for agent.json to make sure it's not
        # readable by others.
        os.chmod("Scalyr/config/templates/agent_config.tmpl", int("640", 8))

        shutil.copy(make_path(agent_source_root, "VERSION"), "Scalyr/VERSION")

        # Copy frozen binary directory (PyInstaller >=6.0 --onedir: exe at root, support files in _internal/).
        dist_dir = os.path.join("dist", "scalyr-agent-2")
        shutil.copytree(dist_dir, "Scalyr/bin", dirs_exist_ok=True)
        # Also copy the same binary as windows service binary.
        # Even if we use the same binary for everything, I couldn't figure out how to make Wix
        # reuse the same file for multiple components. (TODO: figure out how), but it seems that
        # packager compression handles this well and does now increase package size.
        shutil.copy(
            os.path.join(dist_dir, "scalyr-agent-2.exe"), "Scalyr/bin/ScalyrAgentService.exe"
        )
        shutil.copy(
            os.path.join(agent_source_root, "win32/scalyr-agent-2-config.cmd"), "Scalyr/bin"
        )
        shutil.copy(
            make_path(agent_source_root, "win32/ScalyrShell.cmd"),
            "Scalyr/bin/ScalyrShell.cmd",
        )

        run_command(
            'heat dir Scalyr\\bin -cg BIN -dr APPLICATIONBINDIR -srd '
            '-var var.BinFolderSource -t wix-heat-bin-transform.xsl '
            '-gg -sreg -sfrag -out BinComponents.wxs',
            exit_on_fail=True,
            command_name="heat",
        )

        # Copy the cert files.
        # AGENT-283: Certificate validation on windows seems to fail when the intermediate certs are present, skipping them
        cat_files(
            glob_files(make_path(agent_source_root, "certs/*_root.pem")),
            "Scalyr/certs/ca_certs.crt",
            convert_newlines=True,
        )

        # TODO: Check certificate expiration same as we do as part of tox lint target
        # NOTE: This requires us to update Jenkins pipeline and other places where this script is called
        # to install cryptography library

        # Generate a unique identifier used to identify this version of the Scalyr Agent to windows.
        product_code = create_scalyr_uuid3("ProductID:%s:%s" % (variant, version))
        # The upgrade code identifies all families of versions that can be upgraded from one to the other.  So, this
        # should be a single number for all Scalyr produced ones.
        upgrade_code = create_scalyr_uuid3("UpgradeCode:%s" % variant)

        # For prereleases, we use weird version numbers like 4.0.4.pre5.1 .  That does not work for Windows which
        # requires X.X.X.X.  So, we convert if necessary.
        if len(version.split(".")) == 5:
            parts = version.split(".")
            del parts[3]
            version = ".".join(parts)

        run_command(
            'candle -nologo -dVERSION="%s" -dUPGRADECODE="%s" -dPRODUCTCODE="%s" '
            '-dBinFolderSource=Scalyr\\bin scalyr_agent.wxs BinComponents.wxs'
            % (version, upgrade_code, product_code),
            exit_on_fail=True,
            command_name="candle",
        )

        installer_name = "ScalyrAgentInstaller-%s.msi" % version

        run_command(
            "light -nologo -ext WixUtilExtension.dll -ext WixUIExtension -out %s scalyr_agent.wixobj BinComponents.wixobj -v"
            % (output_dir / installer_name),
            exit_on_fail=True,
            command_name="light",
            )
        return installer_name

