#--------------------------------------------------------------------------------------------------
# This dockerfile builds a minimal ubuntu-based image for running a sanity smoketest during the
# automated release process.
#
# It requires the same files/assets as the unified smoke/unit Dockerfile
#
# Example build command:
#   docker build -f <thisfile> -t scalyr/scalyr-agent-ci-sanity:ubuntu.1 .
#--------------------------------------------------------------------------------------------------

FROM ubuntu

RUN apt-get update && apt-get install -y curl python python3
RUN apt-get install -y python3-pip
RUN apt-get install perl
RUN pip3 install requests
RUN apt-get install sudo

#------------------------------------------------------
# Copy and run test scripts
#------------------------------------------------------
COPY unittest smoketest /tmp/
