name: 'Perform deployment.'
description: |
  Prepares current machine by perfroming the set of the deployments, which are defined in the 'agent_build/tools/environment_deployments.deployments.py.' folder.
  For more info, please look at the docs in the same file.'
inputs:
  deployment-name:
    description: "Name of the deployment"
    required: true

  cache-key-runner-part:
    description: | 
      Part of a cache key that represents system and architecture of the current runner. This is needed to provide 
      prevent cache collisions for the same step which runs on different environments.

    default: ${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}
    required: true

  cache-version-suffix:
    description: "Cache key suffix. Can be changed when it is needed to invalidate the cache."
    required: false
    default: v9

runs:
  using: 'node16'
  main: 'dist/index.js'
