FROM amazonlinux:2
RUN yum install -y initscripts python2 python3 gcc
RUN yum install -y python2-pip python2-devel python3-pip python3-devel

COPY dev-requirements.txt dev-requirements.txt

RUN python -m pip install -r dev-requirements.txt
RUN python3 -m pip install -r dev-requirements.txt