name: agent-build-windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre_job:
    name: Skip Duplicate Jobs Pre Job
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Needed for skip-duplicate-jobs job
      contents: read
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281 # v4.0.0
        with:
          cancel_others: 'true'
          github_token: ${{ github.token }}

  build-windows-package:
    name: Build windows MSI installer
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' || github.ref_name == 'master' }}
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r win32\windows-build-requirements.txt

      - name: Build agent package and installer
        run: python build_package.py win32

      - name: Save installer as artifact
        uses: actions/upload-artifact@v3
        with:
          path: ScalyrAgentInstaller-*.msi

      - name: Notify Slack on Failure
        if: ${{ failure() && github.ref_name == 'master' }}
        uses: act10ns/slack@ed1309ab9862e57e9e583e51c7889486b9a00b0f # v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#eng-dataset-cloud-tech'
