name: Build Tarball

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_tarball:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Requirements
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install -r dev-requirements-new.txt

      - name: Build tarball
        run: python build_package_new.py tarball build

      - name: Save tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarball-noarch
          path: build
          retention-days: 1

