name: Benchmarks

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  check-changelog:
    name: Check Changelog
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: install python and requirements
        uses: ./.github/actions/install_python_and_requirements
        with:
          python_version: 3.10

      - name: Check Changelog
        run: |
          python3 build_package_new.py parse-changelog
