name: Retry Workflow Build Container Images

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master
  workflow_dispatch:

  schedule:
    - cron: '0 4 * * *'

jobs:
  retry_workflow:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Retry workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Retrying workflow"
          scripts/cicd/gha/retry_workflow.sh "Build Container Images"
